---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: secret-claim-operator
build:
  artifacts:
    - docker:
        dockerfile: samples/secret-claim-operator/Dockerfile
      image: docker.io/codemowers/secret-claim-operator
deploy:
  kubectl:
    flags:
      global:
        - --namespace=secret-claim-operator
manifests:
  rawYaml:
    - samples/secret-claim-operator/templates/secret-claim-operator-deployment.yaml
