---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: redis-operator
build:
  artifacts:
    - docker:
        dockerfile: samples/redis-operator/Dockerfile
      image: codemowers/redis-operator
deploy:
  kubectl:
    flags:
      global:
        - --namespace=redis-clusters
manifests:
  rawYaml:
    - samples/redis-operator/templates/redis-operator-deployment.yaml
