---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: keydb-operator
build:
  artifacts:
    - docker:
        dockerfile: samples/keydb-operator/Dockerfile
      image: docker.io/codemowers/keydb-operator
deploy:
  kubectl:
    flags:
      global:
        - --namespace=keydb-clusters
manifests:
  rawYaml:
    - samples/keydb-operator/templates/keydb-operator-deployment.yaml
