---
apiVersion: codemowers.cloud/v1beta1
kind: KeydbClass
metadata:
  name: persistent
  annotations:
    kubernetes.io/description: "Persistent KeyDB cluster"
spec:
  reclaimPolicy: Retain
  replicas: 3
  storageClass: redis
  podSpec:
    containers:
      - name: redis
        image: docker.io/eqalpha/keydb@sha256:c6c09ea6f80b073e224817e9b4a554db7f33362e8321c4084701884be72eed67
        imagePullPolicy: IfNotPresent
