---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-bucket-operator
  namespace: minio-clusters
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: minio-bucket-operator
  serviceName: minio-bucket-operator
  template:
    metadata:
      labels:
        app: minio-bucket-operator
    spec:
      containers:
        - image: mirror.gcr.io/codemowers/minio-bucket-operator:latest
          name: minio-bucket-operator
          ports:
            - containerPort: 8000
              name: metrics
          resources:
            limits:
              cpu: 1m
              memory: 128Mi
            requests:
              cpu: '1'
              memory: 64Mi
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      serviceAccountName: codemowers-cloud-minio-bucket-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio-bucket-operator
  name: minio-bucket-operator
  namespace: minio-clusters
spec:
  ports:
    - name: metrics
      port: 8000
      protocol: TCP
  selector:
    app: minio-bucket-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-bucket-operator
  namespace: minio-clusters
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: minio-bucket-operator
