---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codemowers-cloud-minio-bucket-operator
rules:
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - patch
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - codemowers.cloud
    resources:
      - miniobucketclaims
      - miniobucketclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - codemowers.cloud
    resources:
      - miniobucketclaims/status
      - miniobuckets/status
    verbs:
      - patch
      - update
  - apiGroups:
      - codemowers.cloud
    resources:
      - miniobuckets
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - servicemonitors
    verbs:
      - create
      - patch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codemowers-cloud-minio-bucket-operator
  namespace: minio-clusters
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codemowers-cloud-minio-bucket-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codemowers-cloud-minio-bucket-operator
subjects:
  - kind: ServiceAccount
    name: codemowers-cloud-minio-bucket-operator
    namespace: minio-clusters
