---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keydb-operator
  namespace: keydb-clusters
spec:
  enableServiceLinks: false
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: keydb-operator
  serviceName: keydb-operator
  template:
    metadata:
      labels:
        app: keydb-operator
    spec:
      containers:
        - image: mirror.gcr.io/codemowers/keydb-operator:latest
          name: keydb-operator
          ports:
            - containerPort: 8000
              name: metrics
          resources:
            limits:
              cpu: 1m
              memory: 128Mi
            requests:
              cpu: 1000m
              memory: 64Mi
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      serviceAccountName: codemowers-cloud-keydb-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keydb-operator
  name: keydb-operator
  namespace: keydb-clusters
spec:
  ports:
    - name: metrics
      port: 8000
      protocol: TCP
  selector:
    app: keydb-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keydb-operator
  namespace: keydb-clusters
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: keydb-operator
