---
apiVersion: codemowers.cloud/v1beta1
kind: MinioBucketClass
metadata:
  name: shared
  annotations:
    kubernetes.io/description: "Shared Minio cluster"
spec:
  reclaimPolicy: Retain
  shared: true
  replicas: 4
  storageClass: minio
  podSpec:
    containers:
      - name: minio
        image: minio/minio:RELEASE.2023-07-18T17-49-40Z@sha256:8879cd0b0c4087817430e21be3ad909d60e9da62fac3e8d9368d9fde51279229
        imagePullPolicy: IfNotPresent
