---
apiVersion: codemowers.cloud/v1beta1
kind: MinioBucketClass
metadata:
  name: external
  annotations:
    kubernetes.io/description: "External Minio cluster"
spec:
  reclaimPolicy: Retain
  shared: true
