---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-database-operator
  namespace: mysql-clusters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-database-operator
  serviceName: mysql-database-operator
  template:
    metadata:
      labels:
        app: mysql-database-operator
    spec:
      containers:
        - image: docker.io/codemowers/mysql-database-operator:latest
          name: mysql-database-operator
          ports:
            - containerPort: 8000
              name: metrics
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      serviceAccountName: codemowers-cloud-mysql-database-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-database-operator
  name: mysql-database-operator
  namespace: mysql-clusters
spec:
  ports:
    - name: metrics
      port: 8000
      protocol: TCP
  selector:
    app: mysql-database-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-database-operator
  namespace: mysql-clusters
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: mysql-database-operator
