---
apiVersion: codemowers.cloud/v1beta1
kind: RedisClass
metadata:
  name: ephemeral
  annotations:
    kubernetes.io/description: "Ephemeral Redis cluster"
spec:
  reclaimPolicy: Delete
  replicas: 3
  podSpec:
    containers:
      - name: redis
        image: redis:7.0.11@sha256:1008c73f08e9f913868e2fa2e843212b62ea5bf3c66435d87bc7a6207bc0f1b4
        imagePullPolicy: IfNotPresent
