---
apiVersion: codemowers.cloud/v1beta1
kind: RedisClass
metadata:
  name: session
  annotations:
    kubernetes.io/description: "Redis instance for session storage"
spec:
  reclaimPolicy: Delete
  replicas: 3
  podSpec:
    containers:
      - name: redis
        image: docker.io/library/redis:7.0.11@sha256:1008c73f08e9f913868e2fa2e843212b62ea5bf3c66435d87bc7a6207bc0f1b4
        imagePullPolicy: IfNotPresent
        args:
          - --maxmemory-policy
          - volatile-lru
