---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secret-claim-operator
  namespace: secret-claim-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-claim-operator
  serviceName: secret-claim-operator
  template:
    metadata:
      labels:
        app: secret-claim-operator
    spec:
      containers:
        - image: docker.io/codemowers/secret-claim-operator:latest
          name: secret-claim-operator
          ports:
            - containerPort: 8000
              name: metrics
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      serviceAccountName: codemowers-cloud-secret-claim-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: secret-claim-operator
  name: secret-claim-operator
  namespace: secret-claim-operator
spec:
  ports:
    - name: metrics
      port: 8000
      protocol: TCP
  selector:
    app: secret-claim-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secret-claim-operator
  namespace: secret-claim-operator
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: secret-claim-operator
