---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codemowers-cloud-secret-claim-operator
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - codemowers.cloud
    resources:
      - secretclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - codemowers.cloud
    resources:
      - secretclaims/status
    verbs:
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codemowers-cloud-secret-claim-operator
  namespace: secret-claim-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codemowers-cloud-secret-claim-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codemowers-cloud-secret-claim-operator
subjects:
  - kind: ServiceAccount
    name: codemowers-cloud-secret-claim-operator
    namespace: secret-claim-operator
