---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secret-claim-operator
  namespace: secret-claim-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-claim-operator
  serviceName: secret-claim-operator
  template:
    metadata:
      labels:
        app: secret-claim-operator
    spec:
      containers:
        - image: codemowers/secret-claim-operator:latest
          name: secret-claim-operator
          ports:
            - containerPort: 8000
              name: metrics
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      serviceAccountName: codemowers-cloud-secret-claim-operator
