---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codemowers-cloud-postgres-database-operator
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - codemowers.cloud
    resources:
      - postgresdatabaseclaims
      - postgresdatabaseclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - codemowers.cloud
    resources:
      - postgresdatabaseclaims/status
      - postgresdatabases/status
    verbs:
      - patch
      - update
  - apiGroups:
      - codemowers.cloud
    resources:
      - postgresdatabases
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
    verbs:
      - create
      - delete
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codemowers-cloud-postgres-database-operator
  namespace: postgres-clusters
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codemowers-cloud-postgres-database-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codemowers-cloud-postgres-database-operator
subjects:
  - kind: ServiceAccount
    name: codemowers-cloud-postgres-database-operator
    namespace: postgres-clusters
